### ISSUE TITLE
Zen5

### ISSUE THREAD

**Issue by wiltet** [irusanov/SMUDebugTool#12]
Will there be Zen5 supported soon?
I did hear about SMUDebugTool 1.37 working allready.

would be great to have this comming soon for public...

**Comment by irusanov** [comment]
Technically speaking it's a public build, but it's for testing purposes only and is not published on github yet. I've lost quite a bit of motivation to continue working on the projects, this one will eventually be published on github though. Just don't expect quick development.

**Comment by wiltet** [comment]
allright...thanks for your honest answer.

Would really love to see your tool running in other projects like Sp00n`s CoreCycler as well.
Anyway, do what ever you feel like is good.

**Comment by irusanov** [comment]
@wiltet I have uploaded the vesion which people are using for Zen5: https://github.com/irusanov/SMUDebugTool/releases/tag/v1.37
